### ISSUE TITLE
Importing TX details

### ISSUE THREAD

**Issue by sobradob** [pxsocs/cryptoblotter#13]
I'm trying to understand how TX's are updated. Lets imagine a scenario where I do the following:

1. Day 1: Send USD to my CoinBae exchange account.
2. Day 2: Buy BTC with my CoinBae exchange account.
3. Day 3: Buy ETH with my BTC on my CoinBae exchange account. 

Would it look like this?

Timestamp | Account | Operator | Asset | Quantity | Price | Fee | Cash_Value | Notes | trade_reference_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Day1 | Bank | W | EUR | 1000 | 1 | 0 | 1000 | Bank Deposit | 1
Day1 | CoinBae | D | EUR | 1000 | 1 | 0 | 1000 | Deposit Received | 1
Day2 | CoinBae | B | BTC | 0.1 | 5000 | 0 | 500 | BTC Purchase | 2
Day3 | CoinBae | B | ETH | 0.5 | 0.01 | 0 | 50 | ETH/BTC Purchase | 3

**Comment by pxsocs** [comment]
Day 1 Transactions would be ok. You paired the __Withdraw from Bank__ to a __deposit at an exchange__.

Day 2 Transaction would be included fine and would track your BTC position correctly but __you are missing a Withdraw__ in order to track the EUR position correctly (otherwise your CoinBae account would still show a balance of 1,000 EUR).

Day 2 should consist of 2 transactions:
- The one you included under `trade_refence` 2.
- A matching Withdraw of EUR from CoinBae also under `trade_reference` 2

Day 3 would also need to include a matching Withdraw. 

__Important Note:__ At this point all transactions are being tracked in USD. Will add the ability to include other currencies in a future release.
